### ISSUE TITLE
Un-vendor ASL and Mumps

### ISSUE THREAD

**Issue by moorepants** [conda-forge/ipopt-feedstock#48]
Issue:

It seems that ASL and Mumps are being vendored with this package. I  don't think that is what we want to be doing. ASL and Mumps should have their own feedstocks where they are being built as shared libraries and we depend on them. These are the lines in the `meta.yaml` that download the two pieces of software:

```
  - folder: ASL
    url: https://github.com/coin-or-tools/ThirdParty-ASL/archive/releases/1.4.3.tar.gz
    sha256: 0a4cfa7c6c5df72d8e1c4c3ce74633421f807115a679e85cb5569c41df9a9aaf

  - folder: Mumps
    url: https://github.com/coin-or-tools/ThirdParty-Mumps/archive/releases/1.6.2.tar.gz
    sha256: 0cfdd30b9cb42d9539ad9c495629f56dd1fc0b59cea691bbe71a129fabd8895d
    patches:
      - thirdparty-mumps-linux-configure.patch  # [linux]
```

It looks like I approved them in #40 but I can't remember why I did. Maybe I was thinking we were only vendoring for windows?

Regardless, I think this needs to be undone and we setup the proper dependencies on the other conda-forge packages.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>
